In [1]:
import numpy as np

In [7]:
X = np.array([[1,1,1],[2,2,0],[3,3,-1]])
y = np.array([[1],[2],[3]])
print(X)

X_t_X= np.dot(X.T,X)
print(X_t_X)
X_t_y=np.dot(X.T,y)
print(X_t_y)

[[ 1  1  1]
 [ 2  2  0]
 [ 3  3 -1]]
[[14 14 -2]
 [14 14 -2]
 [-2 -2  2]]
[[14]
 [14]
 [-2]]


In [11]:
X = np.array([[1,1],[2,0],[3,-1]])
y = np.array([[1],[2],[3]])
print(X)

X_t_X= np.dot(X.T,X)
print(X_t_X)
X_t_y=np.dot(X.T,y)
print(X_t_y)
print(np.linalg.inv(X_t_X))
w=np.dot(np.linalg.inv(X_t_X),X_t_y)
print(w)

[[ 1  1]
 [ 2  0]
 [ 3 -1]]
[[14 -2]
 [-2  2]]
[[14]
 [-2]]
[[0.08333333 0.08333333]
 [0.08333333 0.58333333]]
[[ 1.00000000e+00]
 [-1.11022302e-16]]
